//! Central ServerTask event loop for coordinating all PeekabooVault operations.
//!
//! This module implements a message-passing architecture that eliminates complex
//! Arc<Mutex<T>> patterns in favor of a single event loop that owns all mutable state.
//!
//! ## Architecture
//!
//! All coordination flows through `ServerMessage` enum sent to the ServerTask's channel.
//! The ServerTask owns:
//! - Camera registry
//! - RTSP client handles
//! - Recorder handles
//! - WebRTC session states
//! - Replay coordinator states
//!
//! ## Benefits
//!
//! - Single source of truth (no race conditions)
//! - Clear message flow (all coordination explicit)
//! - Easy to test (send messages, observe state)
//! - Predictable ordering (sequential message processing)
//! - Simple error handling (failures contained to handlers)

use crate::api::{AddCameraRequest, Camera, CameraStatus, DiscoveredDevice};
use crate::config::Config;
use crate::frame_store::FrameStore;
use crate::hot_cold_db::HotColdDb;
use crate::recorder::RecorderHandle;
use crate::replay_coordinator::ReplayCoordinator;
use crate::rtsp_client::RtspClient;
use crate::state::CameraCredentials;
use anyhow::Context;
use std::collections::HashMap;
use std::sync::Arc;
use tokio::sync::{mpsc, oneshot, RwLock};
use tokio_util::sync::CancellationToken;
use tracing::{debug, error, info, warn};
use uuid::Uuid;

/// Type alias for camera IDs
pub type CameraId = Uuid;

/// Type alias for stream types (e.g., "main", "sub")
pub type StreamType = String;

/// Type alias for session IDs
pub type SessionId = Uuid;

/// All messages that flow through the ServerTask event loop.
///
/// Messages are categorized by source:
/// - HTTP API (with oneshot channels for responses)
/// - RTSP Client (frame data and connection events)
/// - WebRTC Sessions (ICE, data channel commands)
/// - Recorder (segment completion, errors)
/// - Internal (shutdown)
#[derive(Debug)]
pub enum ServerMessage {
    // === HTTP API Messages (queries with oneshot response) ===
    /// Add a new camera to the system
    AddCamera {
        request: AddCameraRequest,
        respond_to: oneshot::Sender<anyhow::Result<Camera>>,
    },

    /// List all cameras
    ListCameras {
        respond_to: oneshot::Sender<Vec<Camera>>,
    },

    /// Get a specific camera by ID
    GetCamera {
        camera_id: CameraId,
        respond_to: oneshot::Sender<Option<Camera>>,
    },

    /// Delete a camera
    DeleteCamera {
        camera_id: CameraId,
        respond_to: oneshot::Sender<Option<Camera>>,
    },

    /// Set credentials for a camera
    SetCredentials {
        camera_id: CameraId,
        credentials: CameraCredentials,
        respond_to: oneshot::Sender<anyhow::Result<()>>,
    },

    /// List discovered devices
    ListDiscoveredDevices {
        respond_to: oneshot::Sender<Vec<DiscoveredDevice>>,
    },

    // === HTTP API Messages (commands, fire-and-forget) ===
    /// Start recording for a camera stream
    StartRecording {
        camera_id: CameraId,
        stream_type: StreamType,
    },

    /// Stop recording for a camera stream
    StopRecording {
        camera_id: CameraId,
        stream_type: StreamType,
    },

    /// Start RTSP client for a camera stream
    StartRtspClient {
        camera_id: CameraId,
        stream_type: StreamType,
        rtsp_url: String,
    },

    /// Stop RTSP client for a camera stream
    StopRtspClient {
        camera_id: CameraId,
        stream_type: StreamType,
    },

    // === RTSP Client Messages ===
    /// Video frame received from RTSP stream
    RtspFrame {
        camera_id: CameraId,
        stream_type: StreamType,
        frame: VideoFrame,
    },

    /// RTSP connection established
    RtspConnected {
        camera_id: CameraId,
        stream_type: StreamType,
        codec_info: CodecInfo,
    },

    /// RTSP connection lost
    RtspDisconnected {
        camera_id: CameraId,
        stream_type: StreamType,
        error: Option<String>,
    },

    // === WebRTC Session Messages ===
    /// ICE candidate generated by WebRTC session
    WebRtcIceCandidate {
        session_id: SessionId,
        candidate: String, // TODO: Use proper ICE candidate type
    },

    /// Data channel message received
    WebRtcDataChannelMessage {
        session_id: SessionId,
        message: DataChannelCommand,
    },

    /// WebRTC session closed
    WebRtcSessionClosed {
        session_id: SessionId,
    },

    // === Recorder Messages ===
    /// Recording segment completed and written to disk
    RecordingSegmentComplete {
        camera_id: CameraId,
        stream_type: StreamType,
        segment_info: SegmentInfo,
    },

    /// Recording error occurred
    RecordingError {
        camera_id: CameraId,
        stream_type: StreamType,
        error: String,
    },

    // === Internal Messages ===
    /// Shutdown the server task
    Shutdown,
}

/// Simplified video frame for message passing
#[derive(Debug, Clone)]
pub struct VideoFrame {
    pub data: Vec<u8>,
    pub timestamp: i64,
    pub is_keyframe: bool,
}

/// Codec information from RTSP connection
#[derive(Debug, Clone)]
pub struct CodecInfo {
    pub codec: String,
    pub width: Option<u32>,
    pub height: Option<u32>,
}

/// Data channel command from WebRTC client
#[derive(Debug, Clone)]
pub enum DataChannelCommand {
    Seek { timestamp: i64 },
    ChangeSpeed { speed: f64 },
    FocusCamera { camera_id: CameraId },
}

/// Information about a completed recording segment
#[derive(Debug, Clone)]
pub struct SegmentInfo {
    pub segment_id: i64,
    pub start_time: i64,
    pub end_time: i64,
    pub bytes: u64,
}

/// State for a camera in the system
#[derive(Debug, Clone)]
struct CameraState {
    camera: Camera,
    credentials: Option<CameraCredentials>,
}

/// Handle for an RTSP client task
struct RtspClientHandle {
    // TODO: Add actual handle fields
    _phantom: std::marker::PhantomData<()>,
}

/// State for a WebRTC session
struct WebRtcSessionState {
    camera_id: CameraId,
    stream_type: StreamType,
    frame_tx: mpsc::Sender<VideoFrame>,
    // TODO: Add more fields as needed
}

/// State for a replay coordinator session
struct ReplayCoordinatorState {
    coordinator: ReplayCoordinator,
    // TODO: Add more fields as needed
}

/// The central event loop that owns all state and routes all messages.
///
/// This is the heart of the message-passing architecture. All coordination
/// happens through messages sent to this task.
pub struct ServerTask {
    // === State owned by ServerTask ===
    /// Camera registry (id -> camera + credentials)
    cameras: HashMap<CameraId, CameraState>,

    /// Discovered devices from ONVIF discovery
    discovered_devices: HashMap<String, DiscoveredDevice>,

    /// Active RTSP clients
    rtsp_clients: HashMap<(CameraId, StreamType), RtspClientHandle>,

    /// Active recorders
    recorders: HashMap<(CameraId, StreamType), RecorderHandle>,

    /// Active WebRTC sessions
    webrtc_sessions: HashMap<SessionId, WebRtcSessionState>,

    /// Active replay sessions
    replay_sessions: HashMap<SessionId, ReplayCoordinatorState>,

    // === Database (queries via spawn_blocking) ===
    /// Hot/Cold database for recording metadata
    hot_cold_db: Arc<RwLock<HotColdDb>>,

    /// Frame store for video data
    frame_store: Arc<FrameStore>,

    // === Configuration ===
    /// Application configuration
    config: Config,

    // === Communication ===
    /// Receiver for incoming messages
    message_rx: mpsc::UnboundedReceiver<ServerMessage>,

    /// Sender for outgoing messages (cloned to clients)
    message_tx: mpsc::UnboundedSender<ServerMessage>,

    // === Shutdown ===
    /// Cancellation token for graceful shutdown
    cancellation_token: CancellationToken,
}

impl ServerTask {
    /// Create a new ServerTask.
    ///
    /// Returns the task and a message sender that can be cloned and shared
    /// with HTTP handlers and other components.
    pub fn new(
        config: Config,
        hot_cold_db: Arc<RwLock<HotColdDb>>,
        frame_store: Arc<FrameStore>,
        cancellation_token: CancellationToken,
    ) -> (Self, mpsc::UnboundedSender<ServerMessage>) {
        let (message_tx, message_rx) = mpsc::unbounded_channel();

        let task = Self {
            cameras: HashMap::new(),
            discovered_devices: HashMap::new(),
            rtsp_clients: HashMap::new(),
            recorders: HashMap::new(),
            webrtc_sessions: HashMap::new(),
            replay_sessions: HashMap::new(),
            hot_cold_db,
            frame_store,
            config,
            message_rx,
            message_tx: message_tx.clone(),
            cancellation_token,
        };

        (task, message_tx)
    }

    /// Run the event loop.
    ///
    /// This processes messages sequentially until shutdown is requested.
    /// Errors in message handlers are logged but don't crash the loop.
    pub async fn run(mut self) {
        info!("ServerTask event loop starting");

        loop {
            tokio::select! {
                Some(msg) = self.message_rx.recv() => {
                    if let Err(e) = self.handle_message(msg).await {
                        error!(error = %e, "Failed to handle message");
                    }
                }
                _ = self.cancellation_token.cancelled() => {
                    info!("ServerTask shutting down");
                    self.shutdown().await;
                    break;
                }
            }
        }

        info!("ServerTask event loop stopped");
    }

    /// Handle a single message.
    ///
    /// This is the central dispatcher that routes messages to their handlers.
    async fn handle_message(&mut self, msg: ServerMessage) -> anyhow::Result<()> {
        match msg {
            // === HTTP API: Queries ===
            ServerMessage::ListCameras { respond_to } => {
                let cameras: Vec<Camera> = self.cameras.values()
                    .map(|state| state.camera.clone())
                    .collect();
                let _ = respond_to.send(cameras);
            }

            ServerMessage::GetCamera { camera_id, respond_to } => {
                let camera = self.cameras.get(&camera_id)
                    .map(|state| state.camera.clone());
                let _ = respond_to.send(camera);
            }

            ServerMessage::DeleteCamera { camera_id, respond_to } => {
                let camera = self.cameras.remove(&camera_id)
                    .map(|state| state.camera);
                let _ = respond_to.send(camera);
            }

            ServerMessage::ListDiscoveredDevices { respond_to } => {
                let devices: Vec<DiscoveredDevice> = self.discovered_devices.values()
                    .cloned()
                    .collect();
                let _ = respond_to.send(devices);
            }

            // === HTTP API: Commands ===
            ServerMessage::AddCamera { request, respond_to } => {
                let result = self.add_camera(request).await;
                let _ = respond_to.send(result);
            }

            ServerMessage::SetCredentials { camera_id, credentials, respond_to } => {
                let result = self.set_credentials(camera_id, credentials).await;
                let _ = respond_to.send(result);
            }

            ServerMessage::StartRecording { camera_id, stream_type } => {
                if let Err(e) = self.start_recording(camera_id, stream_type).await {
                    error!(
                        error = %e,
                        camera_id = %camera_id,
                        "Failed to start recording"
                    );
                }
            }

            ServerMessage::StopRecording { camera_id, stream_type } => {
                self.stop_recording(camera_id, stream_type).await;
            }

            ServerMessage::StartRtspClient { camera_id, stream_type, rtsp_url } => {
                if let Err(e) = self.start_rtsp_client(camera_id, stream_type, rtsp_url).await {
                    error!(
                        error = %e,
                        camera_id = %camera_id,
                        "Failed to start RTSP client"
                    );
                }
            }

            ServerMessage::StopRtspClient { camera_id, stream_type } => {
                self.stop_rtsp_client(camera_id, stream_type).await;
            }

            // === RTSP Events ===
            ServerMessage::RtspFrame { camera_id, stream_type, frame } => {
                self.route_frame(camera_id, stream_type, frame).await?;
            }

            ServerMessage::RtspConnected { camera_id, stream_type, codec_info } => {
                info!(
                    camera_id = %camera_id,
                    stream_type = %stream_type,
                    codec = %codec_info.codec,
                    "RTSP connected"
                );
                // Update camera status
                if let Some(state) = self.cameras.get_mut(&camera_id) {
                    state.camera.status = CameraStatus::Online;
                }
            }

            ServerMessage::RtspDisconnected { camera_id, stream_type, error } => {
                warn!(
                    camera_id = %camera_id,
                    stream_type = %stream_type,
                    error = ?error,
                    "RTSP disconnected"
                );
                // Update camera status
                if let Some(state) = self.cameras.get_mut(&camera_id) {
                    state.camera.status = CameraStatus::Offline;
                }
            }

            // === WebRTC Events ===
            ServerMessage::WebRtcIceCandidate { session_id, candidate } => {
                debug!(session_id = %session_id, "ICE candidate generated");
                // TODO: Send to client via signaling
            }

            ServerMessage::WebRtcDataChannelMessage { session_id, message } => {
                debug!(session_id = %session_id, "Data channel message received");
                // TODO: Handle data channel commands
            }

            ServerMessage::WebRtcSessionClosed { session_id } => {
                info!(session_id = %session_id, "WebRTC session closed");
                self.webrtc_sessions.remove(&session_id);
            }

            // === Recorder Events ===
            ServerMessage::RecordingSegmentComplete { camera_id, stream_type, segment_info } => {
                info!(
                    camera_id = %camera_id,
                    stream_type = %stream_type,
                    segment_id = %segment_info.segment_id,
                    bytes = %segment_info.bytes,
                    "Recording segment completed"
                );
            }

            ServerMessage::RecordingError { camera_id, stream_type, error } => {
                error!(
                    camera_id = %camera_id,
                    stream_type = %stream_type,
                    error = %error,
                    "Recording error"
                );
            }

            // === Internal ===
            ServerMessage::Shutdown => {
                info!("Shutdown message received");
                self.shutdown().await;
            }
        }

        Ok(())
    }

    /// Add a camera to the system.
    async fn add_camera(&mut self, request: AddCameraRequest) -> anyhow::Result<Camera> {
        let camera_id = Uuid::new_v4();

        // TODO: Probe ONVIF device to get device info and stream profiles
        // For now, create a minimal camera
        let camera = Camera {
            id: camera_id,
            name: request.name.clone(),
            onvif_address: Some(request.host.clone()),
            onvif_url: None,
            main_stream_uri: None,
            sub_stream_uri: None,
            stream_profiles: vec![],
            has_credentials: request.username.is_some(),
            status: CameraStatus::Unknown,
            last_seen: None,
            manufacturer: None,
            model: None,
            firmware_version: None,
            serial_number: None,
            hardware_id: None,
        };

        let credentials = if let (Some(username), Some(password)) = (request.username, request.password) {
            Some(CameraCredentials { username, password })
        } else {
            None
        };

        let state = CameraState {
            camera: camera.clone(),
            credentials,
        };

        self.cameras.insert(camera_id, state);

        info!(camera_id = %camera_id, name = %camera.name, "Camera added");

        Ok(camera)
    }

    /// Set credentials for a camera.
    async fn set_credentials(
        &mut self,
        camera_id: CameraId,
        credentials: CameraCredentials,
    ) -> anyhow::Result<()> {
        let state = self.cameras.get_mut(&camera_id)
            .context("Camera not found")?;

        state.credentials = Some(credentials);
        state.camera.has_credentials = true;

        info!(camera_id = %camera_id, "Credentials updated");

        Ok(())
    }

    /// Route a video frame to all consumers.
    ///
    /// This is the central frame distribution point. Frames are sent to:
    /// - Recorder (if recording is active)
    /// - WebRTC sessions (if viewing this camera)
    /// - Replay sessions (if applicable)
    async fn route_frame(
        &mut self,
        camera_id: CameraId,
        stream_type: StreamType,
        frame: VideoFrame,
    ) -> anyhow::Result<()> {
        // Route to recorder
        if let Some(recorder) = self.recorders.get(&(camera_id, stream_type.clone())) {
            if let Some(ref frame_tx) = recorder.frame_tx {
                // Try to send, but don't block if channel is full
                if let Err(_) = frame_tx.send(frame.clone()) {
                    warn!(
                        camera_id = %camera_id,
                        stream_type = %stream_type,
                        "Recorder frame channel closed or full, dropping frame"
                    );
                }
            } else {
                // Recorder not using message-passing architecture yet
                debug!(
                    camera_id = %camera_id,
                    stream_type = %stream_type,
                    "Recorder using old StreamSession architecture"
                );
            }
        }

        // Route to WebRTC sessions viewing this camera
        for (session_id, session) in &mut self.webrtc_sessions {
            if session.camera_id == camera_id && session.stream_type == stream_type {
                // Try to send, but don't block if channel is full
                if let Err(_) = session.frame_tx.try_send(frame.clone()) {
                    warn!(session_id = %session_id, "Frame channel full, dropping frame");
                }
            }
        }

        // Route to replay sessions if applicable
        // For replay, frames are typically read from storage rather than routed live,
        // so this section is intentionally left empty. Replay sessions read frames
        // on-demand from the frame store based on user seek/playback requests.

        Ok(())
    }

    /// Start RTSP client for a camera stream.
    async fn start_rtsp_client(
        &mut self,
        camera_id: CameraId,
        stream_type: StreamType,
        rtsp_url: String,
    ) -> anyhow::Result<()> {
        let key = (camera_id, stream_type.clone());

        // Check if already running
        if self.rtsp_clients.contains_key(&key) {
            return Ok(());
        }

        info!(
            camera_id = %camera_id,
            stream_type = %stream_type,
            rtsp_url = %rtsp_url,
            "Starting RTSP client"
        );

        // TODO: Create and start RTSP client
        // For now, just store a placeholder
        let handle = RtspClientHandle {
            _phantom: std::marker::PhantomData,
        };

        self.rtsp_clients.insert(key, handle);

        Ok(())
    }

    /// Stop RTSP client for a camera stream.
    async fn stop_rtsp_client(&mut self, camera_id: CameraId, stream_type: StreamType) {
        let key = (camera_id, stream_type.clone());

        if let Some(_handle) = self.rtsp_clients.remove(&key) {
            info!(
                camera_id = %camera_id,
                stream_type = %stream_type,
                "Stopped RTSP client"
            );
            // TODO: Actually stop the client
        }
    }

    /// Start recording for a camera stream.
    async fn start_recording(
        &mut self,
        camera_id: CameraId,
        stream_type: StreamType,
    ) -> anyhow::Result<()> {
        let key = (camera_id, stream_type.clone());

        // Check if already recording
        if self.recorders.contains_key(&key) {
            return Ok(());
        }

        info!(
            camera_id = %camera_id,
            stream_type = %stream_type,
            "Starting recording"
        );

        // TODO: Create and start recorder
        // For now, return error as not implemented
        anyhow::bail!("Recording not yet implemented in ServerTask");
    }

    /// Stop recording for a camera stream.
    async fn stop_recording(&mut self, camera_id: CameraId, stream_type: StreamType) {
        let key = (camera_id, stream_type.clone());

        if let Some(_handle) = self.recorders.remove(&key) {
            info!(
                camera_id = %camera_id,
                stream_type = %stream_type,
                "Stopped recording"
            );
            // TODO: Actually stop the recorder
        }
    }

    /// Gracefully shut down all tasks.
    async fn shutdown(&mut self) {
        info!("Shutting down ServerTask");

        // Stop all recorders
        for ((camera_id, stream_type), _handle) in self.recorders.drain() {
            info!(
                camera_id = %camera_id,
                stream_type = %stream_type,
                "Stopping recorder"
            );
            // TODO: Actually stop the recorder
        }

        // Stop all RTSP clients
        for ((camera_id, stream_type), _handle) in self.rtsp_clients.drain() {
            info!(
                camera_id = %camera_id,
                stream_type = %stream_type,
                "Stopping RTSP client"
            );
            // TODO: Actually stop the client
        }

        // Close all WebRTC sessions
        for (session_id, _session) in self.webrtc_sessions.drain() {
            info!(session_id = %session_id, "Closing WebRTC session");
            // TODO: Actually close the session
        }

        info!("ServerTask shutdown complete");
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;
    use tokio_util::sync::CancellationToken;

    #[tokio::test]
    async fn test_server_task_creation() {
        // This is a placeholder test - we need to create mock DB and frame store
        // to properly test ServerTask creation
        let config = Config::default();
        let cancellation_token = CancellationToken::new();

        // TODO: Create mock HotColdDb and FrameStore for testing
        // let (task, tx) = ServerTask::new(config, db, frame_store, cancellation_token);
    }

    #[tokio::test]
    async fn test_message_passing() {
        // TODO: Test that messages can be sent and received
    }
}
