[package]
name = "ptz"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
common.workspace = true
onvif.workspace = true
transport.workspace = true
validate.workspace = true
xml-rs.workspace = true
xsd-macro-utils.workspace = true
xsd-types.workspace = true
yaserde.workspace = true
yaserde_derive.workspace = true
