[package]
name = "accesscontrol"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
transport.workspace = true
types.workspace = true
validate.workspace = true
xml-rs.workspace = true
xsd-macro-utils.workspace = true
xsd-types.workspace = true
yaserde.workspace = true
yaserde_derive.workspace = true
